baseurl: /va-api-landscape

sass:
    style: :compressed
    sass_dir: ./_scss

markdown: kramdown
permalink: /:categories/:title/
github_user: skylight_hq

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md
  - .DS_Store
